### ISSUE TITLE
Cache last updated TLDs for offline builds of tld.js 

### ISSUE THREAD

**Issue by rathann** [hackademix/nscl#3]
[common/tld.js](https://github.com/hackademix/nscl/blob/main/common/tld.js) has not been updated at least since https://github.com/hackademix/nscl/commit/a3f7807d91452c3f61dabd8aba475bad4a3d97cb . I haven't compared the `public_suffix_list.dat` deleted in that commit with the then-current official version, so it might be even older.

**Comment by hackademix** [comment]
This is intended: it's meant to be [updated at inclusion / build time](https://github.com/hackademix/nscl/commit/2dcfd33fc464f66d83416646a5e7eb231a28129b), in order to avoid daily commits.

**Comment by rathann** [comment]
I see. Why keep the file in version control, then?

**Comment by hackademix** [comment]
> Why keep the file in version control, then?

Because there's only one line to be dynamically updated, and I'd like to track any code change in the other 82 ;)

**Comment by rathann** [comment]
Ok. My use case is doing an offline build with no network access (Fedora package), so I can't have `nodejs` fetch the current `public_suffix_list.dat` from upstream and would like to provide our own packaged copy (from `publicsuffix-list` Fedora package). I patched the `update.js` script to run `fs.readFileSync(TLD_CACHE, 'utf8', parse());` instead, but, obviously, a fallback to local copy if network is unavailable would be best. I'm not familiar with NodeJS enough to propose a mergeable patch, though.

**Comment by hackademix** [comment]
> My use case is doing an offline build with no network access (Fedora package)

That's seems a valuable test case. Taking this issue in as a RFE, thanks.

**Comment by rathann** [comment]
That looks perfect for my needs, thank you.
